# Generated by Django 5.1.7 on 2025-04-01 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0003_order_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_of_the_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_orders', to='LittleLemonAPI.customuser'),
        ),
    ]
